make buttons edgy on mobile
nextcloud/firstrunwizard pull request #698
Opened 2022-04-09 16:55 UTC by szaimen

Signed-off-by: szaimen <szaimen@e.mail.de>

2022-04-09 17:34 UTC, szaimen commented
/compile amend /

2022-04-11 10:21 UTC, artonge approved these changes
Code looks good. But let's wait for the design team input before merging.

2022-04-11 10:21 UTC, artonge commented on src/App.vue
> +			.icon-next, .icon-previous {
Add a comment here too ?

2022-04-11 14:05 UTC, szaimen commented on src/App.vue
> +			.icon-next, .icon-previous {
done

2022-04-11 16:40 UTC, jancborchardt requested changes
> Reason for this: I think edgy buttons look better for mobile

:D love the reasoning.

Counter-proposal: We keep the circular buttons, but on mobile we move them to the bottom, with a bit of whitespace to the bottom and each of the sides respectively. Kind of like an Android FAB, but on both sides. Also easier to reach for fingers.

2022-04-11 16:43 UTC, szaimen commented
> Counter-proposal: We keep the circular buttons, but on mobile we move them to the bottom, with a bit of whitespace to the bottom and each of the sides respectively. Kind of like an Android FAB, but on both sides. Also easier to reach for fingers.

Prpblem with moving it to the bottom is that the buttons will overlap the content and other buttons in the templates which looks really weird, in my opinion. That is why they are positioned where they are currently...

2022-04-13 09:47 UTC, nimishavijay commented
Looks interesting! 
Most of our buttons are round (or have a pill-shape) so I'm wondering if it would be consistent with our designs 🤔

2022-04-13 11:43 UTC, szaimen commented
> Looks interesting! Most of our buttons are round (or have a pill-shape) so I'm wondering if it would be consistent with our designs 🤔

Not sure. Please decide and let me know to merge or to close :)

2022-04-14 07:32 UTC, szaimen commented
I am fine with any decision but I need a decision here :)

2022-04-19 09:45 UTC, nimishavijay commented
I would keep the circular buttons, it is consistent with our style :)

2022-04-19 09:46 UTC, szaimen commented
> I would keep the circular buttons, it is consistent with our style :)

okay 👍

2022-04-19 09:46 UTC, closed without merging

2022-04-27 23:58 UTC, jancborchardt commented
Sorry for late reply @szaimen  · regardong the overlap issue, we can make sure that if left/right controls are present, that on mobile there's room for them below the modal?